### ISSUE TITLE
ListStreams?

### ISSUE THREAD

**Issue by sixcorners** [idealo/spring-cloud-stream-binder-sns#74]
Does this have to call ListTopics? I think the io.awspring library has a better way to find the arn. Think it would be worth it to try to find a way to remove this call from the arn resolution/health check?

**Comment by mKeRix** [comment]
There is no technical reason for the ListTopics call other than convenience - we specifically used the same discovery strategy as io.awspring to make it consistent though, as you can see by the reference to their [destination resolver](https://github.com/awspring/spring-cloud-aws/blob/2.4.x/spring-cloud-aws-messaging/src/main/java/io/awspring/cloud/messaging/support/destination/DynamicTopicDestinationResolver.java) [here](https://github.com/idealo/spring-cloud-stream-binder-sns/blob/e0859261d1c737fe4d0067a1b5a8ffad86d683cc/src/main/java/de/idealo/spring/stream/binder/sns/provisioning/SnsStreamProvisioner.java#L20).

If you provide the full ARN instead of just the topic name ListTopics won't be run, instead it will directly use the ARN. I think that leaves a good balance of convenience, consistency and flexibility.

I will close this issue as I believe there is no action required, but feel free to let me know if you disagree and I'll reopen.
